### ISSUE TITLE
Fatal Error

### ISSUE THREAD

**Issue by ElonMusked** [mokoshalb/Meme-Maker-PHP#3]
I did everything as explained in readme, but keep getting this error along with a white screen on index.php which means it's not working.

Fatal error: Call to a member function getMessage() on null in /home/host/public_html/meme/config.php on line 29

What's wrong?

**Comment by OkoyaUsman** [comment]
You probably have an incorrect database details entered.

**Comment by ElonMusked** [comment]
I have no idea what was causing the issue but it worked on my third attempt, thanks!
