### ISSUE TITLE
How do I log in to admin panel

### ISSUE THREAD

**Issue by slam73** [mokoshalb/Meme-Maker-PHP#8]
Hey there,

Thanks for the code.
The admin panel asks me for an email address and password.
I see that I can change this in the database, but the password is probably hashed.
How can I login to the admin panel?

best, Stéphan

**Comment by slam73** [comment]
I temporary removed a piece of code in admin/header.php and I'm in!

**Comment by OkoyaUsman** [comment]
Glad you found a workaround.
